### ISSUE TITLE
Undefined variable: content in class-block-unit-test.php on line 446

### ISSUE THREAD

**Issue by maddisondesigns** [thatplugincompany/block-unit-test#1]
I just installed this plugin. Thanks for creating it.

After activation, it shows the following error:

`Notice: Undefined variable: content in /Volumes/Macintosh HD2/Sites/..../plugins/block-unit-test/class-block-unit-test.php on line 446`

You're doing `.=` on [line 112](https://github.com/thatplugincompany/block-unit-test/blob/master/class-block-unit-test.php#L112). You could either add `$content = '';` on the line before or just change `.=` to `=`;

**Comment by danyj** [comment]
was just about to post this. same thing.

**Comment by richtabor** [comment]
Thanks @maddisondesigns and @danyj — good catch. I'll have it updated here in a few. 👍
